inherit_from: .rubocop_todo.yml

require: rubocop-rspec

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

RSpec/DescribeClass:
  Enabled: false

