language: ruby
script: rake spec
rvm:
  - ruby-head
  - 2.2.3
  - 2.1.5 # developing here, for now
  - jruby-head
  - jruby-9.0.0.0
  - jruby-19mode # jruby-1.7.x in 1.9 mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    - ndushay@stanford.edu
sudo: false