language: ruby
script: rake spec
rvm:
  - ruby-head
  - 2.2.3
  - 2.1.5 # developing here, for now
  - jruby-9.0.0.0
  - jruby-1.7.20
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.0.0 # pry-byebug (interactive debugging gem) doesn't load for jruby
    - rvm: jruby-1.7.20  # pry-byebug doesn't load for jruby
  fast_finish: true
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    - ndushay@stanford.edu
sudo: false